### PR TITLE
Add an HPE copyright to the front matter

### PR DESCRIPTION
**Pull request by RaymondMichael**

### CODE REVIEW

**Comment by RaymondMichael** [comment]
@jdinan I think you were saying I should add a Copyright to the actual standard text.

**Comment by jdinan** [comment]
Can we also include the BSD license text in the front matter?

**Comment by jdinan** [comment]
Do you mind if I post a PR to propose some LaTeX formatting adjustments?

**Comment by RaymondMichael** [comment]
Sure

**Comment by jdinan** [comment]
Here's the proposed formatting: https://github.com/RaymondMichael/specification/pull/37

Screen Shot 2020-04-13 at 11 51 57 AM

**Comment by jdinan** [comment]
@RaymondMichael If the above formatting looks good, please merge https://github.com/RaymondMichael/specification/pull/37 and then this PR. I'm going to build another draft today that contains the doc edits and I will include these changes, as well.

**Comment by swpoole** [comment]
Looks fine.
I have also updated:
http://www.openshmem.org/site/node/58

**Comment by davidozog** [comment]
> @RaymondMichael If the above formatting looks good, please merge #37 and then this PR. 

Slightly confused - shouldn't we merge this PR, then #37?

Either way, consider it approved on my end.  👍

**Comment by jdinan** [comment]
Assuming I did this right, #37 is an update to RaymondMichael:RaymondMichael-patch-2 from jdinan:RaymondMichael-patch-2. This PR (#36) is an update to sec/frontmatter from RaymondMichael-patch-2. So, merging #37 will update this PR. After that, this PR (#36) can be merged. Piece of 🍰. :neckbeard:

**Review by davidozog — APPROVED** [review]

**Pull request merged**
