### PR TITLE
Create footnotes showing contributor roles

### PR DESCRIPTION
**Pull request by RaymondMichael**

### CODE REVIEW

**Review by nspark — COMMENTED** [review]
Two questions:

- I wonder how these footnotes will look when, for subsequent versions, we use (mostly) the same section committees, but the contributors list spans multiple pages. For example, will the footnote for the OpenSHMEM Specification Committee Chair appear on multiple pages?
- Do we want to order the footnotes themselves in the order their respective sections appear in the document?

**Comment by RaymondMichael** [comment]
Yah I realize I'm leaving a problem for future-me, but I don't know enough about TeX to do anything about it.

**Comment by nspark** [comment]
@RaymondMichael I tried adding a couple of the noted positions to the listing of contributors to 1.4. It doesn't duplicate the note at the bottom, which leaves it somewhat unclear to what footnote the mark is referring. I'm okay deferring a fix until 1.6, though.

**Comment by RaymondMichael** [comment]
@nspark or @davidozog, I'll need one of you to approve this.

**Review by davidozog — APPROVED** [review]
Looks great to me.

**Comment by davidozog** [comment]
@nspark @RaymondMichael  In the next release, would it help to move the `\footnotetext` items a bit lower in this section so we could refer to it multiple times with slightly less confusion?

**Review by nspark — APPROVED** [review]

**Comment by nspark** [comment]
@davidozog Maybe. We'll have to experiment a bit, but this looks good for 1.5.

**Pull request merged**
